In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from pathlib import Path

In [2]:
df=pd.read_csv(Path('../data/Cleaned/property.csv'))
df2=pd.read_csv(Path('../data/raw/estate.csv'))

In [3]:
df.isnull().sum()

property_type         0
society               3
price                29
price_per_sqft     2958
sector                0
area                 29
areaWithType          0
bedRoom               0
bathroom              0
balcony              93
address              11
floorNum             20
facing             1152
agePossession         0
nearbyLocations     206
description           0
features            690
rating              411
Pooja Room            0
Study Room            0
Store Room            0
Servant Room          0
Others                0
Size                  0
Type                  0
furnishstatus         0
dtype: int64

In [4]:
df['society']=df['society'].str.lower()
df['society']

0        indiabulls centrum park
1        project mianwali colony
2                     paras dews
3                     rof ananda
4                     sare homes
                  ...
3898         smart world orchard
3899       signature global park
3900     signature global solera
3901    maxworth city residences
3902                  mvn athens
Name: society, Length: 3903, dtype: object

In [5]:
tempdf=df[df['features'].isnull()]
df2['PropertyName']=df2['PropertyName'].str.lower()

In [6]:
x=tempdf.merge(df2,how='left',left_on='society',right_on='PropertyName')['TopFacilities']
df.loc[tempdf.index,'features']=x.values

In [7]:
df.isnull().sum()

property_type         0
society               3
price                29
price_per_sqft     2958
sector                0
area                 29
areaWithType          0
bedRoom               0
bathroom              0
balcony              93
address              11
floorNum             20
facing             1152
agePossession         0
nearbyLocations     206
description           0
features            550
rating              411
Pooja Room            0
Study Room            0
Store Room            0
Servant Room          0
Others                0
Size                  0
Type                  0
furnishstatus         0
dtype: int64

In [8]:
from sklearn.preprocessing import MultiLabelBinarizer
import ast
# Convert the string representation of lists in the 'features' column to actual lists
df['features_list'] = df['features'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) and x.startswith('[') else [])

# Use MultiLabelBinarizer to convert the features list into a binary matrix
mlb = MultiLabelBinarizer()
features_binary_matrix = mlb.fit_transform(df['features_list'])

# Convert the binary matrix into a DataFrame
features_binary_df = pd.DataFrame(features_binary_matrix, columns=mlb.classes_)

In [9]:
features_binary_df.columns

Index(['24/7 Power Backup', '24/7 Water Supply', '24x7 Security', 'ATM',
       'Aerobics Centre', 'Airy Rooms', 'Amphitheatre', 'Badminton Court',
       'Bank Attached Property', 'Banquet Hall',
       ...
       'Visitors Parking', 'Volley Ball Court', 'Waiting Lounge',
       'Waste Disposal', 'Water Softener Plant', 'Water Storage',
       'Water purifier', 'Water softening plant', 'Wi-Fi Connectivity',
       'Yoga/Meditation Area'],
      dtype='object', length=122)

In [10]:
weights = {
    '24/7 Power Backup': 8,
    '24/7 Water Supply': 4,
    '24x7 Security': 7,
    'ATM': 4,
    'Aerobics Centre': 6,
    'Airy Rooms': 8,
    'Amphitheatre': 7,
    'Badminton Court': 7,
    'Banquet Hall': 8,
    'Bar/Chill-Out Lounge': 9,
    'Barbecue': 7,
    'Basketball Court': 7,
    'Billiards': 7,
    'Business Lounge': 9,
    'CCTV Camera Security': 8,
    'Cafeteria': 6,
    'Car Parking': 6,
    'Card Room': 6,
    'Centrally Air Conditioned': 9,
    'Changing Area': 6,
    "Children's Play Area": 7,
    'Cigar Lounge': 9,
    'Clinic': 5,
    'Club House': 9,
    'Concierge Service': 9,
    'Conference room': 8,
    'Creche/Day care': 7,
    'Cricket Pitch': 7,
    'Doctor on Call': 6,
    'Earthquake Resistant': 5,
    'Entrance Lobby': 7,
    'False Ceiling Lighting': 6,
    'Feng Shui / Vaastu Compliant': 5,
    'Fire Fighting Systems': 8,
    'Fitness Centre / GYM': 8,
    'Flower Garden': 7,
    'Food Court': 6,
    'Foosball': 5,
    'Football': 7,
    'Fountain': 7,
    'Gated Community': 7,
    'Golf Course': 10,
    'Grocery Shop': 6,
    'Gymnasium': 8,
    'High Ceiling Height': 8,
    'High Speed Elevators': 8,
    'Infinity Pool': 9,
    'Intercom Facility': 7,
    'Internal Street Lights': 6,
    'Internet/wi-fi connectivity': 7,
    'Jacuzzi': 9,
    'Jogging Track': 7,
    'Landscape Garden': 8,
    'Laundry': 6,
    'Lawn Tennis Court': 8,
    'Library': 8,
    'Lounge': 8,
    'Low Density Society': 7,
    'Maintenance Staff': 6,
    'Manicured Garden': 7,
    'Medical Centre': 5,
    'Milk Booth': 4,
    'Mini Theatre': 9,
    'Multipurpose Court': 7,
    'Multipurpose Hall': 7,
    'Natural Light': 8,
    'Natural Pond': 7,
    'Park': 8,
    'Piped Gas': 7,
    'Pool Table': 7,
    'Power Back up Lift': 8,
    'Private Garden / Terrace': 9,
    'Property Staff': 7,
    'RO System': 7,
    'Rain Water Harvesting': 7,
    'Reading Lounge': 8,
    'Restaurant': 8,
    'Salon': 8,
    'Sauna': 9,
    'Security / Fire Alarm': 9,
    'Security Personnel': 9,
    'Separate entry for servant room': 8,
    'Sewage Treatment Plant': 6,
    'Shopping Centre': 7,
    'Skating Rink': 7,
    'Solar Lighting': 6,
    'Solar Water Heating': 7,
    'Spa': 9,
    'Spacious Interiors': 9,
    'Squash Court': 8,
    'Steam Room': 9,
    'Sun Deck': 8,
    'Swimming Pool': 8,
    'Temple': 5,
    'Toddler Pool': 7,
    'Valet Parking': 9,
    'Video Door Security': 9,
    'Visitor Parking': 7,
    'Water Softener Plant': 7,
    'Water Storage': 7,
    'Water purifier': 7,
    'Yoga/Meditation Area': 7
}
# Calculate luxury score for each row
luxury_score = features_binary_df[list(weights.keys())].multiply(list(weights.values())).sum(axis=1)
df['luxury_score'] = luxury_score

In [11]:
import re
# This function extracts the Super Built up area
def get_super_built_up_area(text):
    match = re.search(r'Super Built up area (\d+\.?\d*)', text)
    if match:
        return float(match.group(1))
    return None
# This function extracts the Built Up area or Carpet area
def get_area(text, area_type):
    match = re.search(area_type + r'\s*:\s*(\d+\.?\d*)', text)
    if match:
        return float(match.group(1))
    return None
# This function checks if the area is provided in sq.m. and converts it to sqft if needed
def convert_to_sqft(text, area_value):
    if area_value is None:
        return None
    match = re.search(r'{} \((\d+\.?\d*) sq.m.\)'.format(area_value), text)
    if match:
        sq_m_value = float(match.group(1))
        return sq_m_value * 10.7639  # conversion factor from sq.m. to sqft
    return area_value
# Extract Super Built up area and convert to sqft if needed
df['super_built_up_area'] = df['areaWithType'].apply(get_super_built_up_area)
df['super_built_up_area'] = df.apply(lambda x: convert_to_sqft(x['areaWithType'], x['super_built_up_area']), axis=1)

# Extract Built Up area and convert to sqft if needed
df['built_up_area'] = df['areaWithType'].apply(lambda x: get_area(x, 'Built Up area'))
df['built_up_area'] = df.apply(lambda x: convert_to_sqft(x['areaWithType'], x['built_up_area']), axis=1)

# Extract Carpet area and convert to sqft if needed
df['carpet_area'] = df['areaWithType'].apply(lambda x: get_area(x, 'Carpet area'))
df['carpet_area'] = df.apply(lambda x: convert_to_sqft(x['areaWithType'], x['carpet_area']), axis=1)
df[['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].sample(5)

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
1872,0.50,house,100.00,Built Up area: 100 (9.29 sq.m.),NaN,100.0,NaN
2353,2.08,flat,1727.00,Super Built up area 1727(160.44 sq.m.),1727.0,NaN,NaN
2923,1.35,flat,990.32,Carpet area: 92,NaN,NaN,92.0
883,1.83,flat,2325.29,Super Built up area 2325(216 sq.m.),2325.0,NaN,NaN
1406,18.00,house,4518.00,Plot area 502(419.74 sq.m.),NaN,NaN,NaN

In [12]:
df[df['areaWithType'].str.contains('Plot')][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].head(5)

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
7,0.700,house,1160.0,Plot area 1160(107.77 sq.m.),NaN,NaN,NaN
11,0.525,house,360.0,Plot area 360(33.45 sq.m.),NaN,NaN,NaN
12,0.300,house,50.0,Plot area 50(4.65 sq.m.),NaN,NaN,NaN
13,5.800,house,4518.0,Plot area 502(419.74 sq.m.),NaN,NaN,NaN
23,14.000,house,3510.0,Plot area 390(326.09 sq.m.),NaN,NaN,NaN

In [13]:
all_nan_df = df[((df['super_built_up_area'].isnull()) & (df['built_up_area'].isnull()) & (df['carpet_area'].isnull()))][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']]
all_nan_df.head()

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
7,0.700,house,1160.0,Plot area 1160(107.77 sq.m.),NaN,NaN,NaN
11,0.525,house,360.0,Plot area 360(33.45 sq.m.),NaN,NaN,NaN
12,0.300,house,50.0,Plot area 50(4.65 sq.m.),NaN,NaN,NaN
13,5.800,house,4518.0,Plot area 502(419.74 sq.m.),NaN,NaN,NaN
23,14.000,house,3510.0,Plot area 390(326.09 sq.m.),NaN,NaN,NaN

In [14]:
all_nan_index = df[((df['super_built_up_area'].isnull()) & (df['built_up_area'].isnull()) & (df['carpet_area'].isnull()))][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].index
# Function to extract plot area from 'areaWithType' column
def extract_plot_area(area_with_type):
    match = re.search(r'Plot area (\d+\.?\d*)', area_with_type)
    return float(match.group(1)) if match else None
all_nan_df['built_up_area'] = all_nan_df['areaWithType'].apply(extract_plot_area)

# Update the original dataframe
#gurgaon_properties.update(filtered_rows)

df.update(all_nan_df)

In [15]:
df.drop(columns=['address','nearbyLocations','description','features','rating','Size','Type','features_list'],inplace=True)
df.to_csv('property_v2.csv',index=False)

In [16]:
df.head()

,property_type,society,price,price_per_sqft,sector,area,areaWithType,bedRoom,bathroom,balcony,...,Pooja Room,Study Room,Store Room,Servant Room,Others,furnishstatus,luxury_score,super_built_up_area,built_up_area,carpet_area
0,flat,indiabulls centrum park,2.45,NaN,sector 103,2875.25,Super Built up area 2875(267.1 sq.m.),4,4,3.0,...,1,1,1,1,0,0,38,2875.0,NaN,NaN
1,house,project mianwali colony,2.00,14815.0,mianwali colony,1350.00,Built Up area: 1350 (125.42 sq.m.),5,5,2.0,...,0,0,0,0,0,0,0,NaN,1350.0,NaN
2,flat,paras dews,1.50,NaN,sector 106,2355.16,Super Built up area 2355(218.79 sq.m.)Built Up...,4,6,3.0,...,0,0,0,1,0,0,174,2355.0,1535.0,1403.000000
3,flat,rof ananda,0.38,NaN,sector 95,549.21,Carpet area: 549.17 (51.02 sq.m.),2,2,1.0,...,0,0,0,0,0,1,0,NaN,NaN,549.174178
4,flat,sare homes,0.68,NaN,sector 92,1298.21,Carpet area: 1298 (120.59 sq.m.),3,3,2.0,...,1,0,0,0,0,1,100,NaN,NaN,1298.000000